name: pst
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - pyg 
  - lightning 
  - pytorch-scatter 
  - pytorch-cluster
  - pip:
      - proteinshake 
      - fair-esm 
      - pyprojroot 
      - einops
      - pandas 
      - easydict 
      - pyprojroot 
      - scikit-learn
      - hydra-core 
      - tensorboard 