defaults:
  - _self_
  - training: debug
  - mode: default

debug: true
seed: 1234
  
data:
  organism: swissprot
  datapath: datasets/AlphaFold/${data.organism}
  graph_eps: 8.0
  crop_len: 1024
  mask_rate: 0.15
  val_datapath: datasets/dms

compute:
  accelerator: gpu
  precision: 16-mixed
  strategy: ddp
  num_workers: 8
  n_jobs: 10

logs:
  prefix: logs/test_logs/
  path: ${logs.prefix}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  
model:
  name: "esm2_t6_8M_UR50D"
  k_hop: 2
  train_struct_only: false
  use_edge_attr: true
  gnn_type: gine
  edge_dim: null

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
