defaults:
  - _self_
  - task: enzyme_class

seed: 1234
model: esm2_t6_8M_UR50D
use_edge_attr: false
datapath: datasets
split: structure
batch_size: 4
num_workers: 4
device: null

truncation_seq_length: 5000
toks_per_batch: 4096
include_seq: false
struct_only: false

pretrained: pretrained/${model}

logs:
  prefix: logs_pst/proteinshake
  path: ${logs.prefix}/${task.name}/${model}/${split}/${seed}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/${task.name}/${model}/${split}/${seed}
    subdir: ""
