defaults:
  - _self_

seed: 1234
model: esm2_t6_8M_UR50D
batch_size: 4
num_workers: 1
device: null

truncation_seq_length: 5000
toks_per_batch: 4096
include_seq: false
struct_only: false

pretrained:
  prefix: pretrained/${model}
  name: model.pt

logs:
  prefix: logs_inference
  path: ${logs.prefix}/${model}/${seed}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/${model}/${seed}
    subdir: ""