defaults:
  - _self_
  - dataset: gearnet_ec

task:
  class: MultipleBinaryClassification
  model:
    output_dim: 0
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
  criterion: bce
  num_mlp_layer: 0
  metric: ['auprc@micro', 'f1_max']

seed: 1234
model: esm2_t6_8M_UR50D
use_edge_attr: false
datapath: datasets
nogpu: false
solver: mlp
metric: 'f1_max'
batch_size: 4
num_workers: 4
device: null

truncation_seq_length: 5000
toks_per_batch: 4096
include_seq: false
aggr: concat
use_pca: null


pretrained: pretrained/${model}

logs:
  prefix: logs_proteinshake/gearnet
  path: ${logs.prefix}/${dataset.name}/${solver}/${model}/${aggr}/${include_seq}/${seed}

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/${dataset.name}/${solver}/${model}/${aggr}/${include_seq}/${seed}
    subdir: ""
